name: tiger-fasttrack-card
services:
- name: api
  source_dir: /
  github:
    repo: tiger-fasttrack-card
    branch: main
    deploy_on_push: true
  run_command: ./tiger-fasttrack-card
  environment_slug: go
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
  envs:
  - key: ENVIRONMENT
    value: production
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: ${DATABASE_URL}
  - key: DB_HOST
    value: ${DB_HOST}
  - key: DB_PORT
    value: ${DB_PORT}
  - key: DB_USER
    value: ${DB_USER}
  - key: DB_PASSWORD
    value: ${DB_PASSWORD}
  - key: DB_NAME
    value: ${DB_NAME}
  - key: DB_SSLMODE
    value: require
  - key: JWT_SECRET
    value: ${JWT_SECRET}

databases:
- name: tiger-card-db
  engine: PG
  version: "15"

# Optional: Add static site for frontend if needed
# static_sites:
# - name: frontend
#   github:
#     repo: tiger-fasttrack-card-frontend
#     branch: main
#   build_command: npm run build
#   output_dir: dist
